<?php
$titles=
[
"Air guns LSP",
"Air Reservoir CRVZS",
"Ball valves and ball valve actuator units VZBA",
"Cartridge cylinder and multimount cylinder",
"Clip fix tool AGTC",
"Compact, short stroke and flat cylinder",
"Control cabinets",
"Cylinder with clamping unit",
"Drives with displacement encoder",
"Drives with guide rods",
"Drives with slide",
"Electrical peripherals",
"Linear actuators, Copac DLP",
"Linear drive with DFPI displacement encoder",
"Linear drives",
"Magnetic coupling",
"Mechanical coupling",
"Modules",
"Multi-position cylinders",
"Pilot valves",
"Pinch valves VZQA",
"Pneumatic valves VLX",
"Pressure regulators LR, LRS",
"Proportional directional control valves",
"Quarter turn actuators DFPD",
"Reverse jet pulse valves VZWE",
"Round cylinders",
"Sensor interfaces",
"Solenoid valves MN1H",
"Solenoid valves VZWP",
"Spiral tubing – PUN-S, PUN-S-DUO",
"Spiral Tubing PPS",
"Stainless steel cylinders",
"Standard cylinder DNC, metric",
"Standards based valve terminals",
"Swivel-linear drive units",
"Tandem and high-force cylinders",
"Universal valve terminals",
"Standards-based cylinders",
"Spiral Tubing PUN-SG",
"Accessories for linear actuators DFPI",
"Accessories for quarter turn actuators",
"Accessories for valve terminals",
"Air blower nozzles LPZ",
"Air Reservoir VZS",
"AMTC AMTE U UC UO UOM UOMS UOS Silencer",
"Angle seat valves VZXF",
"Application-specific valve terminals",
"Axis controllers",
"Ball valve drive units VZPR",
"Ball valves and ball valve actuator units VZBC",
"Cables and accessories",
"Compressed air filter – FRC, FRCS",
"Couplings for sensor box drive",
"Displacement encoders",
"Inscription label holders",
"Inscription labels ASLR BZ HWF IBS KM KMC/F/V MH SBS",
"Integration solutions",
"Linear modules",
"Mounting kits",
"Mounting Plates",
"Plastic-coated metal tube PM",
"Pneumatic pressure present indicator OH",
"Pneumatic terminal block LT LTE LTV",
"Positioners",
"PQ-AL",
"PQ-PA",
"PUN-H, PUN-H-DUO",
"PUN, PUN-DUO",
"Quarter turn actuators DAPS",
"Semi-rotary drives with rack and pinion",
"Semi-rotary drives with rotary vane",
"Sensor boxes",
"Solenoid valve MN1H",
"Solenoid valves supplementary product line MCH, MFH",
"Solenoid valves VZWD",
"Solenoid valves VZWF",
"Solenoid valves VZWM",
"Standard O.D. tubing",
"Universal directional control valve CPE",
"VAPB ball valves",
];
$filenames =[
'PLUG-COM-ROSCA-MACHO-fullWidthDesktop.jpg',
'PLUG-COM-ESPIGAO-PARA-TUBO-DE-BORRACHA-fullWidthDesktop.jpg',
'RACCORDO-DIRITTO-FEMMINA-fullWidthDesktop-300x300.jpg',
'RACCORDO-A-L-INTERMEDIO-fullWidthDesktop-1-300x300.jpg',
'RACCORDO-A-T-MASCHIO-CONICO-fullWidthDesktop-1-300x300.jpg',
'RACCORDO-A-T-INTERMEDIO-fullWidthDesktop-1-300x300.jpg',
'SOQUETE-COM-ROSCA-MACHO-fullWidthDesktop-300x300.jpg',
'SOQUETE-COM-ROSCA-FEMEA-fullWidthDesktop-300x300.jpg',
'SOQUETE-COM-CONEXAO-PUSH-ON-fullWidthDesktop-300x300.jpg',
'SOQUETE-COM-ROSCA-MACHO-fullWidthDesktop-300x300.jpg',
'SOQUETE-COM-ESPIGAO-PARA-MANGUEIRA-DE-BORRACHA-fullWidthDesktop-1-300x300.jpg',
'PLUG-COM-ROSCA-MACHO-fullWidthDesktop-1.jpg',
'RACCORDO-A-CROCE-INTERMEDIO-fullWidthDesktop-1-300x300.jpg',
'CONEXAO-EM-T-TUBO-TUBO-fullWidthDesktop.jpg',
'CONEXAO-EM-T-COM-ROSCA-MACHO-LATERAL-fullWidthDesktop-300x300.jpg',
'CONEXAO-EM-L-TUBO-TUBO-fullWidthDesktop-300x300.jpg',
'CONEXAO-RETA-TUBO-TUBO-fullWidthDesktop.jpg',
'CONEXAO-PASSAMURO-TUBO-TUBO-fullWidthDesktop-300x300.jpg',
'CONEXAO-RETA-COM-ROSCA-MACHO-PARALELA-COM-O-RING-fullWidthDesktop-300x300.jpg',
'CONEXAO-TIPO-CRUZETA-TUBO-TUBO-fullWidthDesktop-300x300.jpg',
'ADAPTADOR-ORIENTAVEL-COM-ROSCA-MACHO-PARALELA-fullWidthDesktop.jpg',
'ESPIGAO-PARA-ENGATE-DE-MANGUEIRAS-fullWidthDesktop.jpg',
'RACCORDO-ORIENTABILE-A-L-CON-VITE-fullWidthDesktop-300x300.jpg',
'CONEXAO-EM-L-ORIENTAVEL-COM-PARAFUSOS-E-ARRUELA-BI-MATERIAL-1613-fullWidthDesktop-300x300.jpg',
'CONEXAO-EM-T-ORIENTAVEL-COM-PARAFUSOS-E-ARRUELA-BI-MATEIRAL-16-3-fullWidthDesktop-300x300.jpg',
'REDUCAO-fullWidthDesktop-300x300.jpg',
'PORCA-fullWidthDesktop.jpg',
'BUCHA-EM-LATAO-fullWidthDesktop.jpg',
'CONEXAO-ESPIGADO-FEMEA-PARA-TUBO-AUTOBLOCANTE-fullWidthDesktop-300x300.jpg',
'ARRUELA-BI-MATERIAL-EM-ACO-E-NBR-fullWidthDesktop.jpg',
'TUBO-AUTOBLOCCANTE-fullWidthDesktop-300x300.jpg',
'CONEXAO-EM-T-COM-ROSCA-MACHO-CENTRAL-fullWidthDesktop-300x300.jpg',
'RONDELLA-IN-ALLUMINIO-fullWidthDesktop-300x300.jpg',
'RONDELLA-BIMATERIALE-IN-ACCIAIO-E-NBR-fullWidthDesktop-300x300.jpg',
'DADO-DI-BLOCCAGGIO-CON-MOLLA-fullWidthDesktop-300x300.jpg',
'TAGLIATUBO-IN-TECNOPOLIMERO-fullWidthDesktop-300x300.jpg',
'PISTOLA-DI-SOFFIAGGIO-OE-6-mm-ATTACCO-FEMMINA-IN-TECNOPOLIMERO-fullWidthDesktop-300x300.jpg',
'PISTOLA-DI-SOFFIAGGIO-OE-6-mm-CON-ATTACCO-FEMMINA-IN-METALLO-fullWidthDesktop-300x300.jpg',
'PISTOLA-DI-SOFFIAGGIO-OE-6-mm-INOX-CON-TUBO-RICURVO-SUPER-SILENZIOSA-fullWidthDesktop-300x300.jpg',
'PISTOLA-DI-SOFFIAGGIO-DI-SICUREZZA-A-3-5-BAR-CON-TUBO-RICURVO-DA-OE-8-mm-fullWidthDesktop-300x300.jpg',
'SOQUETE-COM-ROSCA-MACHO-fullWidthDesktop-1.jpg',
'SOQUETE-COM-ROSCA-FEMEA-fullWidthDesktop-1.jpg',
'SOQUETE-COM-ESPIGAO-PARA-TUBO-DE-BORRACHA-fullWidthDesktop.jpg',
'ANELLO-ORIENTABILE-A-L-fullWidthDesktop-300x300.jpg',
'REGOLATORE-UNIDIREZIONALE-ORIENTABILE-PER-CILINDRO-UNIVERSAL-SHORT-REGOLAZIONE-A-CACCIAVITE-fullWidthDesktop-300x300.jpg',
'REGOLATORE-UNIDIREZIONALE-ORIENTABILE-PER-CILINDRO-UNIVERSAL-SHORT-CON-SPINTORE-NERO-REGOLAZIONE-A-CACCIAVITE-fullWidthDesktop-300x300.jpg',
'VITE-CAVA-TRIPLA-fullWidthDesktop-300x300.jpg',
'REGOLATORE-UNIDIREZIONALE-ORIENTABILE-PER-CILINDRO-FILETTO-CILINDRICO-REGOLAZIONE-A-CACCIAVITE-fullWidthDesktop-300x300.jpg',
'REGOLATORE-DI-FLUSSO-UNIDIREZIONALE-ORIENTABILE-PER-CILINDRO-REGOLAZIONE-A-CACCIAVITE-fullWidthDesktop-300x300.jpg',
'RACCORDO-DIRITTO-MASCHIO-CONICO-fullWidthDesktop-1-300x300.jpg',
'RACCORDO-DIRITTO-INTERMEDIO-fullWidthDesktop-300x300.jpg',
'RACCORDO-A-L-MASCHIO-CONICO-fullWidthDesktop-300x300.jpg',
'RACCORDO-A-L-ORIENTABILE-MASCHIO-CONICO-fullWidthDesktop-300x300.jpg',
'RACCORDO-DIRITTO-MASCHIO-CILINDRICO-fullWidthDesktop-300x300.jpg',
'RACCORDO-DIRITTO-FEMMINA-fullWidthDesktop-1-300x300.jpg',
'RACCORDO-DIRITTO-INTERMEDIO-fullWidthDesktop-2-300x300.jpg',
'RACCORDO-A-L-MASCHIO-CONICO-fullWidthDesktop-2-300x300.jpg',
'RACCORDO-A-L-ORIENTABILE-MASCHIO-CILINDRICO-fullWidthDesktop-300x300.jpg',
'RACCORDO-A-T-ORIENTABILE-MASCHIO-LATERALE-CILINDRICO-fullWidthDesktop-300x300.jpg',
'RACCORDO-A-T-INTERMEDIO-fullWidthDesktop-2-300x300.jpg',
'RACCORDO-DIRITTO-MASCHIO-UNIVERSAL-SHORT-fullWidthDesktop-300x300.jpg',
'RACCORDO-DIRITTO-INTERMEDIO-fullWidthDesktop-1-300x300.jpg',
'RACCORDO-DIRITTO-INTERMEDIO-DI-ATTRAVERSAMENTO-fullWidthDesktop-300x300.jpg',
'RACCORDO-A-L-MASCHIO-CONICO-fullWidthDesktop-1-300x300.jpg',
'RACCORDO-A-L-INTERMEDIO-fullWidthDesktop-300x300.jpg',
'RACCORDO-A-T-MASCHIO-CONICO-fullWidthDesktop-300x300.jpg',
'RACCORDO-A-T-INTERMEDIO-fullWidthDesktop-300x300.jpg',
'DADO-fullWidthDesktop-300x300.jpg',
'PLUG-EM-ACO-COM-ROSCA-MACHO-fullWidthDesktop.jpg',
'PLUG-EM-ACO-COM-ROSCA-FEMEA-fullWidthDesktop.jpg',
'PLUG-EM-ACO-COM-ESPIGAO-PARA-TUBO-DE-BORRACHA-fullWidthDesktop.jpg',
'VALVOLA-FEMMINA-RP-ISO-7-FEMMINA-RP-ISO-7-fullWidthDesktop-300x300.jpg',
'PRESA-CON-ATTACCO-MASCHIO-UNIVERSAL-SHORT-fullWidthDesktop-300x300.jpg',
'PRESA-CON-ATTACCO-FEMMINA-fullWidthDesktop-300x300.jpg',
'INNESTO-CON-ATTACCO-MASCHIO-UNIVERSAL-SHORT-EUROPEAN-DN-7.8-fullWidthDesktop-300x300.jpg',
'INNESTO-CON-ATTACCO-FEMMINA-EUROPEAN-DN-7.8-fullWidthDesktop-300x300.jpg',
'VALVOLA-MASCHIO-CONICO-R-ISO-7-TUBO-fullWidthDesktop-300x300.jpg',
'SOQUETE-COM-ROSCA-MACHO-fullWidthDesktop-2.jpg',
'SOQUETE-COM-ROSCA-FEMEA-fullWidthDesktop-2.jpg',
'SOQUETE-COM-CONEXAO-PUSH-ON-fullWidthDesktop-1.jpg',
'REGOLATORE-DI-FLUSSO-BIDIREZIONALE-REGOLAZIONE-A-CACCIAVITE-fullWidthDesktop-300x300.jpg',
'VALVULA-BORBOLETA-PARAFUSOS-PORCAS-ARRUELAS-fullWidthDesktop-300x300.jpg',
'UGELLO-DIRITTO-RICAMBIO-fullWidthDesktop-300x300.jpg',
'UGELLO-ANGOLATO-RICAMBIO-fullWidthDesktop-300x300.jpg',
'UGELLO-EFFETTO-VENTURI-RICAMBIO-fullWidthDesktop-300x300.jpg',
'PISTOLA-DI-SOFFIAGGIO-ATTACCO-FEMMINA-fullWidthDesktop-300x300.jpg',
'PISTOLA-DI-SOFFIAGGIO-CON-SCHERMO-D-ARIA-PROTETTIVO-ATTACCO-FEMMINA-fullWidthDesktop-300x300.jpg',
'PISTOLA-DI-SOFFIAGGIO-ATTACCO-A-CALZAMENTO-CON-MOLLA-fullWidthDesktop-300x300.jpg',
'PISTOLA-DI-SOFFIAGGIO-CON-SCHERMO-D-ARIA-PROTETTIVO-ATTACCO-A-CALZAMENTO-CON-MOLLA-fullWidthDesktop-300x300.jpg',
'CLIP-DI-SICUREZZA-fullWidthDesktop-300x300.jpg',
'RACCORDO-DIRITTO-MASCHIO-CILINDRICO-fullWidthDesktop-1-300x300.jpg',
'RACCORDO-DIRITTO-INTERMEDIO-fullWidthDesktop-3-300x300.jpg',
'RACCORDO-A-L-ORIENTABILE-MASCHIO-CILINDRICO-fullWidthDesktop-1-300x300.jpg',
'RACCORDO-A-T-ORIENTABILE-MASCHIO-CILINDRICO-fullWidthDesktop-300x300.jpg',
'RACCORDO-A-T-INTERMEDIO-fullWidthDesktop-3-300x300.jpg',
'VALVOLA-DADO-CAPETTATO-MASCHIO-CONICO-R-ISO-7-fullWidthDesktop-1-300x300.jpg',
'VALVOLA-A-L-MASCHIO-CILINDRICO-GA-ISO-228-MASCHIO-CONICO-R-ISO-7-fullWidthDesktop-300x300.jpg',
'TUBO-IN-POLIAMIDE-RIGIDO-fullWidthDesktop-300x300.jpg',
'OGIVA-OTTONE-fullWidthDesktop-1-300x300.jpg',
'OGIVA-OTTONE-fullWidthDesktop-300x300.jpg',
'FILTRO-Y-fullWidthDesktop-300x300.jpg',
'VALVOLA-DI-FONDO-fullWidthDesktop-300x300.jpg',
'FILTRO-IN-RETE-STIRATA-fullWidthDesktop-300x300.jpg',
'VALVOLA-3-VIE-A-T-FEMMINA-G-ISO-228-fullWidthDesktop-300x300.jpg',
'TUBOS-EM-ALUMINIO-CALIBRADOS-DE-COR-AZUL-4-MT-fullWidthDesktop.jpg',
'CONEXAO-RETA-COM-ROSCA-MACHO-fullWidthDesktop-212x300.jpg',
'CONEXAO-RETA-INTERMEDIARIA-fullWidthDesktop-231x300.jpg',
'CONEXAO-TIPO-COTOVELO-fullWidthDesktop.jpg',
'CONEXAO-PARA-SAIDA-DE-AR-fullWidthMobile.jpg',
'SAIDA-DE-AR-DUPLA-fullWidthDesktop-1-287x300.jpg',
'SAIDA-DE-AR-DUPLA-fullWidthDesktop.jpg',
'SAIDA-DE-AR-DUPLA-INCLINADA-TUBO-ROSCA-FEMEA-NPTF-fullWidthDesktop-300x300.jpg',
]; 

?>